# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ToDoList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ToDoList

  pod 'SwiftLint', '0.48.0'
  pod 'CocoaLumberjack'
  pod 'SnapKit', '~> 5.6.0'

  target 'ToDoListTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
